#!/bin/bash

# echo "[post-commit hook] Commit done!"

# # Allows us to read user input below, assigns stdin to keyboard
# exec < /dev/tty

# while true; do
#   read -p "[post-commit hook] Check for outdated gems? (Y/n) " yn
#   if [ "$yn" = "" ]; then
#     yn='Y'
#   fi
#   case $yn in
#       [Yy] ) bundle outdated --pre; break;;
#       [Nn] ) exit;;
#       * ) echo "Please answer y or n for yes or no.";;
#   esac
# done
