name: panvimdoc

on:
  push:
    paths:
      - '**.md'

jobs:
  docs:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    steps:
      - uses: actions/checkout@v2
      - name: panvimdoc
        uses: nekowinston/panvimdoc@main
        with:
          vimdoc: catppuccin
          description: "Soothing pastel theme for NeoVim"
          pandoc: "README.md"
          toc: true
          version: "nvim 0.7"
          demojify: true
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto generate docs"
          branch: ${{ github.head_ref }}
